### PR TITLE
Check for global before checking its prop

### PR DESCRIPTION
**Pull request by gotjoshua**
Trying to get dexie syncable round trip in https://blog.stackblitz.com/posts/introducing-webcontainers/

### CODE REVIEW

**Comment by dfahlander** [comment]
Thanks.

**Comment by gotjoshua** [comment]
> Thanks.

welcome! thanks for your amazing product/project!

when do you expect this change to be published to npm (with the next version i guess)?

**Comment by dfahlander** [comment]
Will do a new release within the coming 2 weeks. The publish script will then also publish dexie-observable if we have bumped its version number. I do that now so it won't be missed.

**Comment by dfahlander** [comment]
It's released on in dexie-observable@3.0.0-beta.11.

**Pull request merged**
