### PR TITLE
Do not leak arguments

### PR DESCRIPTION
**Pull request by YuriSolovyov**
Prevent leaking of arguments according to [Optimization guide](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments)

### CODE REVIEW

**Comment by YuriSolovyov** [comment]
sorry, I didn't get the `The arguments object must not be passed or leaked anywhere.` part.
to really not leak the args, you still need to do this inline.

**Comment by YuriSolovyov** [comment]
@dfahlander do you want me to open a new PR with inline args copying?

**Comment by dfahlander** [comment]
Not sure if it's worth it. I would suppose that type of optimization is
disappearingly small compared the time it takes to perform a db operation.
Maybe in some places (functions that are frequently called from within
loops) it could be.
Den 2 sep 2015 20:46 skrev "Yuri" <notifications@github.com>:

**Comment by dfahlander** [comment]
In 1.4.0-beta, I've got rid of all leaking arguments.

**Pull request closed without merging**
