### PR TITLE
Performance boost

### PR DESCRIPTION
**Pull request by jimmywarting**

### CODE REVIEW

**Comment by dfahlander** [comment]
Thanks. Need to fix slice() though because it has to be used with apply() or bind().
Would you have a chance to run the unit tests in Chrome and Mozilla? Just open dexie/test/run-unit-tests.html in you browsers and wait for them to complete.

Thanks again,
David

**Comment by jimmywarting** [comment]
601 assertions of 601 passed, 0 failed. both chrome and firefox. don't see any problem with apply or bind...?

**Comment by dfahlander** [comment]
Ok, I must have looked at it too fast. missed out that you already wrapped _slice with a function that did _slice.call().

**Comment by dfahlander** [comment]
I put you add a contributor, so if you find more nice things to improve, please go ahead and commit directly. I can review before releasing to dist and npm.

**Comment by jimmywarting** [comment]
Sweet, thanks!

**Pull request merged**
