### PR TITLE
Base schema upgrade on current schema information from the database

### PR DESCRIPTION
**Pull request by joseprio**
Mitigates the problem described in #942

### CODE REVIEW

**Comment by dfahlander** [comment]
This looks like an elegant solution. Thanks a lot! I've briefly reviewed the changes but want to do it more thoroughly before merging it in.

**Comment by timbru31** [comment]
Ouch! This PR breaks the update mechanism completely :(
Since the `buildGlobalSchema` function is used, the `unique (&)` flag is lost, because `createIndexSpec` (see line 300) always passes false.

This results in a diff like this:

Screenshot 2020-02-25 at 18 10 40

Therefore, the `recreate` flag will be set and Dexie stops with the `UpgradeError` error:
Screenshot 2020-02-25 at 18 09 58


Before this PR, the old schema is used (via `oldVersionStruct._cfg.dbschema;`) and the `recreate` flag is `false`:
Screenshot 2020-02-25 at 18 16 55


The diff between our two version is the following:

```ts
		versions.push({
			versionNumber: 2,
			stores: {
				walksheet: '++id',
				order: '&uuid,created,modified,status',
				buildings: '&geb_id,adresse,strasse',
				people: '&kundenr,vorname,nachname'
			}
		});
		versions.push({
			versionNumber: 3,
			stores: {
				walksheet: '++id,&plz,lastImport',
				order: '&uuid,created,modified,status',
				buildings: '&geb_id,adresse,strasse,plz',
				people: '&kundenr,vorname,nachname'
			}
		});
```


As you can see, it should only add new indices.
Please correct me if I'm wrong, but IMO this is a major regression.

**Comment by joseprio** [comment]
This only applies for the primary key; is it possible the table was created
manually?

**Comment by timbru31** [comment]
No every interaction with the IndexedDB is made through Dexie. Tables were created by Dexie v2 though.

**Comment by joseprio** [comment]
Ok, I think that the problem here is that uuid being the primary key makes
it inherently unique, and therefore that ampersand has no effect.

In a way, I’d argue that declaring it unique is incorrect, as unique
indices are not the same as primary keys.

**Comment by timbru31** [comment]
Indeed the docs state `Detail: Primary keys are implicitly marked as unique.` - given the fact that it worked quite well since years, I'd argue that explicitly marking a primary key as unique should not cause any issues (as in our case).  

I'll debug tomorrow if what happens if I remove the explicit uniqueness (&)

**Comment by dfahlander** [comment]
It's ok to declare primary key as being unique. I've seen people do that in order to be more explicit. I think we must account for that in the upgrade function and not regard the primary key as changed in case the uniqueness differs, as primary keys are unique not matter how they were declared. I suppose it is an easy fix in schema-helpers.ts when checking if the primary key differs or not.

We should create a repro of this issue in test-upgrade.js and fix before releasing 3.0.0.

**Comment by dfahlander** [comment]
I will not have the time this week so if anyone would have the time, that would be perfect. Otherwise I try fix it next week.

**Comment by timbru31** [comment]
As expected, the migration runs successfully without the explicit unique modifier.

I've create a WIP PR here that adds a, currently, failing test:https://github.com/dfahlander/Dexie.js/pull/984

Hopefully I'll have enough time tomorrow or friday to come up with a fix for the failing test ;)

**Pull request merged**
