### PR TITLE
WIP: Refactor observable

### PR DESCRIPTION
**Pull request by nponiros**
Long standing PR to refactor Dexie.Observable.

### CODE REVIEW

**Comment by nponiros** [comment]
What is tests-observable-misc supposed to test? I'm guessing "test1" tests if the second database gets informed about changes in the first database. "Capital$$Id-test" seems to be testing if "$$Id" actually creates an ID.

There are also two functions in there (lines 85 and 170) which don't seem to be called ever. Should those be called? Unfortunately I can not tell what those are testing since most comments are not in english. Are those functions even relevant?

**Comment by dfahlander** [comment]
Haven't touched those tests for ages. I think they might be very sloppy written. Sorry :(

**Comment by nponiros** [comment]
Okay, I will see what I can do about it. Google translate might help :p

**Comment by nponiros** [comment]
We should probably put sendMessage() and broadcastMessage() under the db.observable namespace since these are function defined by Dexie.Observable. This will also match what Dexie.Syncable does with the functions it defines.

**Comment by nponiros** [comment]
So I think this is enough refactoring for now. I pulled some functions out of Dexie.Observable, added some unit tests and integration tests and I also added the tests to travis.sh and release.sh.

There is still more that we could refactor but I will not have so much time in the next few months and I don't want to start something which I can not finish. If everything looks good feel free to merge @dfahlander .

**Pull request merged**
