### PR TITLE
dexie-react-hooks

### PR DESCRIPTION
**Pull request by dfahlander**
New library: dexie-react-hooks.

Based on PR #1172.

See the libs/dexie-react-hooks/test for example usage.

Basically allows app developers load indexedDB data and keep their component updated whenever the data changes.

Inspired by @rakeshpai's [suggestion](https://github.com/dfahlander/Dexie.js/issues/1141#issuecomment-717259766)

# Syntax

```ts

export function useLiveQuery<T, TDefault=undefined> (
  querier: () => Promise<T> | T,
  deps?: any[], // ...like deps for useMemo(). Defaults to empty array.
  defaultResult?: TDefault // Default value returned while data is loading
) : T | TDefault;

```

# Example

This example shows that...
- you can observe the result of an arbritary function that queries Dexie
- mix it with useState() and let state affect a paremeter to the query.
- you can choose whether to query dexie inline or do it via a callback property.
- the component will re-render if in-parameter to the query change.
- the component will re-render if the data you are querying change

```jsx

function MyComponent () {
  const [fromAge, setFromAge] = useState(18);
  const friendCount = useLiveQuery(()=>db.friends.count());
  const friends = useLiveQuery(
    ()=>db.friends.where('age').above(fromAge).toArray(),
    [fromAge]
  );

  // If default values are returned, queries are still loading:
  if (!friends || friendCount === undefined) return null;
  
  return <div>
    <label>
      From age: <input
        type="number"
        value={fromAge}
        onChange={ev => setFromAge(parseInt(ev.target.value))}
      />
    </label>
    <p>Your have {friendCount} friends in total.</p>
    <p>Here are the names of all friends over the age of {fromAge}:</p>
    <ul>
      {
        friends.map(friend =>
          <li key={friend.id}>
            {friend.name}, {friend.age}
            <button onClick={() => db.friends
                .where({id: friend.id})
                .modify(f => ++f.age)}>
              Birthday!
           </button>
          </li>
        )
      }
    </ul>
  </div>;
}

```
As you can see in this sample, the expressions passed to useLiveQuery() can be any expression that returns a promise. If you don't want to tie the component to the dexie logic, you can provide a fetcher in your props and it will still be observed:

```jsx
function MyComponent ({fetchFriendCount, fetchFriendsByAge, onBirthdayClick}) {
  ...
  const friendCount = useLiveQuery(fetchFriendCount);
  const friends = useLiveQuery(()=>fetchFriendsByAge(fromAge), [fromAge]);
  ...
      // And the button's onClick event:
      <button ... onClick={()=>onBirthdayClick(friend)}>...</button>
}

// Let app declare the fetchers:

function App () {
   const fetchFriendCount = () => db.friends.count();
   const fetchFriendsByAge = fromAge => db.friends.where('age').above(fromAge).toArray();
   const onBirthdayClick = friend => db.friends
    .where({id: friend.id})
    .modify(friend => ++friend.age);
   
  return <MyComponent
    fetchFriendCount={fetchFriendCount}
    fetchFriendsByAge={fetchFriendsByAge}
    onBirthdayClick={onBirthdayClick} />;
}

// Or if you want to stub it:

const DUMMY_FRIENDS = [{id: 1, name: "Foo", age: 33}];

function TestComponent () {
  const [friends, setFriends] = useState(DUMMY_FRIENDS);
  const fetchFriendCount = () => friends.length;
  const fetchFriendsByAge = fromAge => friends.filter(f => f.age >= fromAge);
  const onBirthdayClick = friend =>
    setFriends(friends => friends.map(f => f.id === friend.id ? {...f, age: f.age + 1} : f));
   
  return <MyComponent
    fetchFriendCount={fetchFriendCount}
    fetchFriendsByAge={fetchFriendsByAge}
    onBirthdayClick={onBirthdayClick} />;
}

```

### CODE REVIEW

**Comment by ttessarolo** [comment]
I've just published this (not yet documented). Happy to hear what you think:

https://github.com/ttessarolo/useDexie

**Comment by dfahlander** [comment]
> I've just published this (not yet documented). Happy to hear what you think:
> 
> https://github.com/ttessarolo/useDexie

Your library would be much nicer than using dexie with redux. However, there seems to be quite some hooks and parameter names to learn.

My PR aims to solve the data fetching using an unopinionated approach that only introduce a single new hook. See the samples I just update the PR description with.

**Comment by rakeshpai** [comment]
This is awesome! Thanks a ton for this, @dfahlander! It might be a while before we can use this in our prod app, but I'll definitely give it a spin on a toy project and give you feedback if any. Thanks again!

**Comment by dfahlander** [comment]
@rakeshpai Thank you for your example repo and pushing for this!

If you want to play with it, you could fork a stackblitz demo I created today: https://stackblitz.com/edit/dexie-todo-list

**Pull request merged**
