### PR TITLE
Workaround for Safari issue with getAll().

### PR DESCRIPTION
**Pull request by dfahlander**
Resolves issue #565

### CODE REVIEW

**Comment by timbru31** [comment]
This breaks the performance of e.g. Chrome, too and even the Safari (iOS 10.3, iOS 11) versions which do support IndexdedDB 2.0 and the *getAll*  method.
Chrome user agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36`

See my [stackoverflow question/issue ](https://stackoverflow.com/q/46475404/1902598) regarding very, very bad performance. Testing with getAll instead results in 10x faster loading times for us.
Please consider reverting this issue.

**Comment by dfahlander** [comment]
@timbru31 Thanks. I never like UA sniffing, but need to find a way to work around the bug of Safari idintified in [the more recent comments of issue 565](https://github.com/dfahlander/Dexie.js/issues/565#issuecomment-324679947). If I roll back this PR we will get issues again on Safari: Version 10.1.2 (12603.3.8).

Any idea someone?

**Comment by nponiros** [comment]
Hm maybe `navigator.vendor` can help? On Mac OS Safari the vendor is "Apple Computer, Inc.". You should be able to detect Safari with this but you will probably have issues on iOS Chrome which will probably (didn't test) give vendor "Google Inc." although parts of Safari are used under the hood.

**Comment by timbru31** [comment]
Besides that, getAll works fine for me on iOS 10.3 and iOS 11 - I'd like to keep support for these, too.

**Comment by nponiros** [comment]
We might be able to combine the vendor with the version from the userAgent but the test will probably be rather brittle..

**Comment by timbru31** [comment]
navigator.appVersion might help to detect the iOS versions: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/appVersion (deprecated though :/)

**Comment by nponiros** [comment]
appVersion on Mac OS Safari is basically the same as userAgent minus the "Mozilla" at the beginning of the UA string..

**Comment by dfahlander** [comment]
The issue in Safari 10.1 on iOS 10.3 is rather severe. Repro: http://dexie.org/test/dexie-issue-565/

**Comment by dfahlander** [comment]
Output: Testing Safari issue with IDBObjectStore.getAll()

Status: Preventing eternal reload. Last status was: Could put item. Now trying IDBObjectStore.getAll()

navigator.userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E269 Safari/602.1

navigator.vendor: Apple Computer, Inc.

navigator.appVersion: 5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E269 Safari/602.1

**Comment by dfahlander** [comment]
Also on desktop mac, same issue:

navigator.userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

navigator.vendor: Apple Computer, Inc.

navigator.appVersion: 5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Comment by dfahlander** [comment]
Could someone try [the repro](http://dexie.org/test/dexie-issue-565/) on a newer Safari version to see if it is solved? Note that this happens from a WebWorker calling IDBObjectStore.getAll().

Unless we can see a non-failing Safari version, we need to keep preventing using getAll() on Safari. If getting (but keep Chrome untouched of course)

**Comment by timbru31** [comment]
iPad with iOS 11.1 (15B5066f) is fine:
img_b81283582225-1

---
iPhone with iOS 11.0.1 (15A402) is fine

img_3395740420d7-1

**Comment by timbru31** [comment]
However, I noticed that running the code outside a Worker, the web page did not reload - this means we need to detect a Worker environment and the special Safari versions?

**Comment by dfahlander** [comment]
Ok, great, so Safari 604 is fine but not <603. What about the following:

```js
hasGetAll = 'getAll' in store &&
                !(/Apple/.test(navigator.vendor) &&
                  [].concat(navigator.userAgent.match(/Safari\/(\d*)/))[1] < 604);
```

**Comment by timbru31** [comment]
What about the WebWorker check, too? Something like this could work: https://stackoverflow.com/a/18002694/1902598

**Comment by dfahlander** [comment]
I haven't checked that it's only an issue in workers. I'll test now.

**Comment by dfahlander** [comment]
You're right. I can fix it only for workers. But I found that navigator.vendor is not accessable from workers :(  only navigator.userAgent seem to be accessable. So I have to do something else than /Apple/.test(navigator.vendor). Suggestion?

**Comment by dfahlander** [comment]
I've updated the check to:

```js
// Bug with getAll() on Safari ver<604 on Workers only, see discussion following PR #579
if (/Safari/.test(navigator.userAgent) &&
    !/Chrome/.test(navigator.userAgent) &&
    _global.WorkerGlobalScope && _global instanceof _global.WorkerGlobalScope &&
    [].concat(navigator.userAgent.match(/Safari\/(\d*)/))[1] < 604)
{
    hasGetAll = false;
}    
```
Thoughts?

**Comment by dfahlander** [comment]
Ah! Edge also has "Safari" in UA! Another false positive. Need to update yet again.

```js
if (/Safari/.test(navigator.userAgent) &&
    !/(Chrome\/|Edge\/)/.test(navigator.userAgent) &&
    _global.WorkerGlobalScope && _global instanceof _global.WorkerGlobalScope &&
    [].concat(navigator.userAgent.match(/Safari\/(\d*)/))[1] < 604)
{
    hasGetAll = false;
}    
```

**Comment by Sopamo** [comment]
Sorry for opening this issue up again. I'm pretty sure I'm running into this issue again on an iPhone SE iOS 10.3 emulator using a webkit view (cordova). `navigator.userAgent` reports: 
`Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E8301` which doesn't contain "Safari", so the user agent sniffing doesn't work in this case. I'm currently unable to check if the issue only affects emulated devices because I do not own an iOS device running iOS 10. I'd be pretty surprised if the user agent differs between a real device and an emulator though.
Upon calling table.toArray() the app just crashes. Loading a single item via .get() works fine.

**Comment by dfahlander** [comment]
If you use dexie@3 it will work the same on all browsers.

**Pull request merged**
